### ISSUE TITLE
Error loading JCudaRuntime in 0.13.3 and 0.14.0 on Mac

### ISSUE THREAD

**Issue by neolee** [uncomplicate/neanderthal#29] opened 2017-07-03 09:48 UTC
MacBook Pro, macOS Sierra 10.12.5
GPU: AMD Radeom R9 M270X (Note: So I always use OpenCL for computing on this machine, no CUDA related software installed.)

The following lines are copied from the Hello World example, which worked perfectly with neanderthal 0.13.2 and earlier versions.

```
(require '[uncomplicate.commons.core :refer [with-release]])
(require '[uncomplicate.clojurecl.core :refer [with-platform platforms with-context context with-queue sort-by-cl-version devices]])
(require '[uncomplicate.clojurecl.legacy :refer [with-default-1 command-queue-1]])
(require '[uncomplicate.neanderthal.core :refer [asum]])
(require '[uncomplicate.neanderthal.opencl :refer [clv with-default-engine]])
```

But when I change the dependency in project.clj from 0.13.2 to 0.13.3 OR 0.14.0, the following error spawned when execute the last line:

```
CompilerException java.lang.UnsatisfiedLinkError: Error while loading native library "JCudaRuntime-0.8.0-apple-x86_64"
Operating system name: Mac OS X
Architecture         : x86_64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaRuntime-0.8.0-apple-x86_64 in java.library.path
……
Stack trace from the attempt to load the library as a resource:
java.lang.UnsatisfiedLinkError: /private/var/folders/pj/spb2zy094gn2kkt8wnsdmn6h0000gn/T/libJCudaRuntime-0.8.0-apple-x86_64.dylib: dlopen(/private/var/folders/pj/spb2zy094gn2kkt8wnsdmn6h0000gn/T/libJCudaRuntime-0.8.0-apple-x86_64.dylib, 1): Library not loaded: @rpath/CUDA.framework/Versions/A/CUDA
  Referenced from: /private/var/folders/pj/spb2zy094gn2kkt8wnsdmn6h0000gn/T/libJCudaRuntime-0.8.0-apple-x86_64.dylib
  Reason: image not found
……
```

I guess that in between 0.13.2 and 0.13.3 some dependency on JCuda imported even if only OpenCL implementation used.

If any further info needed please tell me here. BTW very much thanks for bring us so cool lib!

**Comment by blueberry** [comment] 2017-07-03 09:54
I found where the issue is, and the fix will be in Neanderthal 0.15.0. It will take a while since I am in the middle of adding lots of new features, but I expect it to be ready before end of July. I hope 0.13.2 is currently OK for you, or you are in a hurry?

Thank you for reporting this. Since I have both AMD and Nvidia GPUs in my machine it is difficult to me to discover these kinds of regressions. Please report such issues as soon as you can in the future :)

**Comment by neolee** [comment] 2017-07-03 09:56
Thanks! For now 0.13.2 is very OK for me :)

**Closed** 2017-07-03 09:59 UTC

**Comment by blueberry** [comment] 2017-09-01 15:25
@neolee Can you please test whether this works OK now in 0.15.0?

**Comment by neolee** [comment] 2017-10-17 03:05
Sorry for late, because kind of busy recently :)

I've tested on the newest 0.16.1 release and all works well, except parsing error due to API (svd! related) changes, which is irrelevant to this issue.

Thanks again!
